-- init.sql - PostgreSQL schema for NIOSH app

-- NOTE:
-- - Questo script presume che tu sia già connesso al database corretto.
-- - È pensato per Postgres (Supabase, Render Managed Postgres, ecc.).

BEGIN;

-- Utenti
CREATE TABLE IF NOT EXISTS t_user (
    uid            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(100) UNIQUE NOT NULL,
    password       VARCHAR(255) NOT NULL, -- bcrypt hash già crittografato
    creation_date  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    online         SMALLINT DEFAULT 0,
    last_heartbeat TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_t_user_username ON t_user(username);
CREATE INDEX IF NOT EXISTS idx_t_user_online   ON t_user(online);

-- Log accessi
CREATE TABLE IF NOT EXISTS t_log (
    log_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid       INT NOT NULL,
    op_type   SMALLINT NOT NULL, -- 0=logout, 1=login
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_kiosk  SMALLINT NOT NULL DEFAULT 0,
    ip_address  VARCHAR(45),
    user_agent  VARCHAR(500),
    CONSTRAINT fk_tlog_user FOREIGN KEY (uid) REFERENCES t_user(uid) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_t_log_uid       ON t_log(uid);
CREATE INDEX IF NOT EXISTS idx_t_log_timestamp ON t_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_t_log_op_type   ON t_log(op_type);

-- Valutazioni NIOSH
CREATE TABLE IF NOT EXISTS t_niosh_evaluations (
    eval_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 INT NOT NULL,
    eval_name           VARCHAR(255),
    weight              NUMERIC(10,2),
    horizontal_distance NUMERIC(10,2),
    vertical_distance   NUMERIC(10,2),
    vertical_height     NUMERIC(10,2),
    distance_moved      NUMERIC(10,2),
    asymmetric_angle    NUMERIC(10,2),
    frequency           NUMERIC(10,2),
    duration            VARCHAR(50),
    grip_quality        VARCHAR(50),
    rwl                 NUMERIC(10,2),
    li                  NUMERIC(10,2),
    created_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_eval_user FOREIGN KEY (uid) REFERENCES t_user(uid) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_niosh_uid        ON t_niosh_evaluations(uid);
CREATE INDEX IF NOT EXISTS idx_niosh_created_at ON t_niosh_evaluations(created_at);

-- Audit di sicurezza (opzionale)
CREATE TABLE IF NOT EXISTS t_security_audit (
    audit_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(50) NOT NULL, -- failed_login, forced_logout, etc
    uid        INT NULL,
    details    TEXT NULL,
    timestamp  TIMESTAMPTZ NOT NULL,
    ip_address VARCHAR(45)
);

CREATE INDEX IF NOT EXISTS idx_security_audit_event_type ON t_security_audit(event_type);
CREATE INDEX IF NOT EXISTS idx_security_audit_timestamp  ON t_security_audit(timestamp);

-- Admin user (password: admin123) - CAMBIARE la hash in produzione!
INSERT INTO t_user (uid, username, password)
VALUES (1, 'admin', '$2y$10$YourHashedPasswordHere')
ON CONFLICT (uid) DO NOTHING;

COMMIT;


